### ISSUE TITLE
Array.protoype.includes requires node 6.4.0

### ISSUE THREAD

**Issue by derikb** [andresdavid90/tumblr-lks-downldr#13]
I don't see any node version requirements in the Readme but with the recent include of Array.prototype.includes in the code, that mean you need node 6.4.0+ installed to run the code. (I was on 4.5.0 and the code failed.)

Not sure if that needs mentioning somewhere, or if we should add a polyfill for older versions.

**Comment by derikb** [comment]
And I just learned we can define this is in package.json with 

```
"engines": {
  "node": ">=6.4.0"
}
```

**Comment by andrscrrn** [comment]
@derikb Actually, we should be supporting from Node 4. I'm fixing this. Thanks!
