### ISSUE TITLE
Rename downloaded files to something meaningful

### ISSUE THREAD

**Issue by derikb** [andresdavid90/tumblr-lks-downldr#8]
The default tumblr filenames are meaningless and random.
Renaming to "{blogname}_{timestamp}" would help to keep grouped images together (when there are multiple per post) and make identification/attribution easier.

I've got this working on a fork, but it needs the feature I added to pizza-guy to be accepted before this will work non-locally. Will submit a pull request if/when that gets updated (so I can put the correct version in the package.json file).

**Comment by andrscrrn** [comment]
I'll be out until next week but I'll take a look after that @derikb. Thank you for this and all the other contributions! 🙌🏻

**Comment by andrscrrn** [comment]
Hi @derikb. The functionality about renaming files is already merged in `pizza-guy`, but if you see my comments in your current open pull request, I think this can be useful but just for a few people. I would like to see this as an optional functionality. What do you think? Maybe we can actually have a few different options.

**Comment by andrscrrn** [comment]
@derikb This is already implemented right? Not totally sure. Can you please check and close this if it is necessary?

**Comment by derikb** [comment]
Yes. Closing.
