### ISSUE TITLE
Option to save text note with post content

### ISSUE THREAD

**Issue by derikb** [andresdavid90/tumblr-lks-downldr#9]
I care about attribution, so adding a text note with the content of the post would help. In combo with #8 an option to save a note with the text of the post. The note would be named with the same format as the images "{blogname}_{timestamp}" so it would sort with them in a filesystem. Use a html2text converter to make the content text (in desktop gui txt files will often preview so you can immediately see the text as you browse the images).

I've got this working locally in conjunction with my pizza-guy pull request and #8. Will submit a pull request if/when pizza-guy gets that feature incorporated.

**Comment by andrscrrn** [comment]
I like this new feature but I can't merge it now since it is thigh right now with the renaming feature where I have a few comments about. Can you maybe separate these two things? So I can merge this first.

**Comment by derikb** [comment]
Should be able to do a pull request for just this issue in the next couple days.

**Comment by andrscrrn** [comment]
Whenever you have time, no rush. Thanks! 👍🏻

**Comment by derikb** [comment]
Actually... I'm not sure how to do this without the image filename change.

With the filename change, I was giving all the images a name based on the blogname and the timestamp (then a number if there were multiple images in the post). The post's textual content was then added with that same filename as a txt file. That way they'd all be identified together based on the filename prefix.

Without changing the filename of the images, I don't have a way to name the post txt file in a way that would connect it to the image files. You'd end up with just more random files in the directory and no idea which text went with which images.

**Comment by andrscrrn** [comment]
Since we are now making the filename change optional, what we can do is to change the name also if the user is asking for text notes. At the end how you said, the user would be looking for attribution for these cases and having both things working at the same time makes a lot of sense.

**Comment by andrscrrn** [comment]
@derikb I'm not totally sure but this feature was already implemented right? Can we close this?

**Comment by derikb** [comment]
Yes.

On Dec 11, 2016 2:47 AM, Andrés Carreño <notifications@github.com> wrote:

@derikb<https://github.com/derikb> I'm not totally sure but this feature was already implemented right? Can we close this?
